---
id: groonga-meetup-20140429
base_name: groonga-meetup-20140429
tags: []
presentation_date: 2014/04/29
version: 2014.04.29.1
licenses: []
slideshare_id:
speaker_deck_id: 
ustream_id: 
vimeo_id: 
author:
  markup_language: 
  name: HAYASHI Kentaro
  email: hayashi@clear-code.com
  rubygems_user: kenhys
  slideshare_user: kenhys
  speaker_deck_user: 
